apiVersion: apps/v1
kind: Deployment
metadata:
    name: crashloop-demo
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: crashloop-demo
    template:
        metadata:
            labels:
                app: crashloop-demo
        spec:
            containers:
                - name: crashloop
                  image: busybox
                  command: ['sh', '-c', 'echo Starting... && exit 1']
