apiVersion: v1
kind: Pod
metadata:
    name: crashloop-pod
    namespace: default
spec:
    restartPolicy: Always
    containers:
        - name: crashloop
          image: busybox
          command: ['sh', '-c', 'echo Starting && exit 1']
