apiVersion: v1
kind: Pod
metadata:
    name: oom-pod
    namespace: default
spec:
    restartPolicy: Always
    containers:
        - name: memory-hog
          image: polinux/stress
          args: ['--vm', '1', '--vm-bytes', '500M', '--vm-hang', '1']
          resources:
              limits:
                  memory: '100Mi'
