apiVersion: apps/v1
kind: Deployment
metadata:
    name: oom-deployment
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: oom-test
    template:
        metadata:
            labels:
                app: oom-test
        spec:
            containers:
                - name: memory-hog
                  image: polinux/stress
                  command: ['stress']
                  args: ['--vm', '1', '--vm-bytes', '500M', '--vm-hang', '1']
                  resources:
                      limits:
                          memory: '100Mi'
                      requests:
                          memory: '50Mi'
